export const STAGES=["new","qualified","offer_sent","payment_pending","paid","case_active","closed_lost"] as const;
export type Stage=(typeof STAGES)[number];
const ALLOWED:Record<Stage,readonly Stage[]>={new:["qualified","closed_lost"],qualified:["offer_sent","closed_lost"],offer_sent:["payment_pending","closed_lost"],payment_pending:["paid","closed_lost"],paid:["case_active","closed_lost"],case_active:["closed_lost"],closed_lost:[]};
export function isStage(value:unknown):value is Stage{return typeof value==="string"&&(STAGES as readonly string[]).includes(value)}
export function canTransition(from:Stage,to:Stage,context?:{provider_evidence_id?:string|null;loss_reason?:string|null}):boolean{
 if(!isStage(from)||!isStage(to))return false;
 if(from===to)return true;if(!ALLOWED[from].includes(to))return false;
 if(to==="paid"&&!context?.provider_evidence_id)return false;
 if(to==="closed_lost"&&!context?.loss_reason?.trim())return false;
 return true;
}
export type LeadInput={full_name:string;email:string;phone:string|null;whatsapp:string|null;country:string;service_category:string;preferred_contact_method:"email"|"whatsapp"|"phone";message:string;consent:true;source:"landing"|"whatsapp"|"meta"|"referral"|"manual"};
const MAX:Record<string,number>={full_name:200,email:320,phone:40,whatsapp:40,country:100,service_category:120,message:4000};
const CONTACT_METHODS=["email","whatsapp","phone"] as const;
export function validateLead(input:unknown):{ok:true;value:LeadInput}|{ok:false;errors:string[]}{if(!input||typeof input!=="object")return{ok:false,errors:["body must be an object"]};const x=input as Record<string,unknown>,errors:string[]=[];for(const key of ["full_name","email","country","service_category","message"]){if(typeof x[key]!=="string"||!String(x[key]).trim())errors.push(key+" is required");else if(String(x[key]).trim().length>MAX[key])errors.push(key+" is too long")}if(typeof x.email==="string"&&!/^\S+@\S+\.\S+$/.test(x.email.trim()))errors.push("email is invalid");for(const key of ["phone","whatsapp"])if(x[key]!==undefined&&x[key]!==null&&typeof x[key]!=="string")errors.push(key+" must be a string or null");for(const key of ["phone","whatsapp"])if(typeof x[key]==="string"&&x[key].trim().length>MAX[key])errors.push(key+" is too long");if(!CONTACT_METHODS.includes(x.preferred_contact_method as typeof CONTACT_METHODS[number]))errors.push("preferred_contact_method is invalid");if(x.consent!==true)errors.push("consent is required");if(!["landing","whatsapp","meta","referral","manual"].includes(String(x.source)))errors.push("source is invalid");if(errors.length)return{ok:false,errors};return{ok:true,value:{full_name:String(x.full_name).trim(),email:String(x.email).trim(),phone:x.phone==null?null:String(x.phone).trim()||null,whatsapp:x.whatsapp==null?null:String(x.whatsapp).trim()||null,country:String(x.country).trim(),service_category:String(x.service_category).trim(),preferred_contact_method:x.preferred_contact_method as LeadInput["preferred_contact_method"],message:String(x.message).trim(),consent:true,source:x.source as LeadInput["source"]}}}