import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const domain = await readFile("nilecare-landing/lib/domain.ts", "utf8");
const migration = await readFile("supabase/001_nilecare_core.sql", "utf8");
const posts = JSON.parse(await readFile("content-bank/posts.json", "utf8"));
assert.match(domain, /validateLead/);
assert.match(domain, /canTransition/);
assert.match(migration, /unique\(event_type, external_id\)/);
assert.equal(posts.expected_count, 80);
assert.deepEqual(posts.approved_posts, []);
console.log("NILECARE_SELF_CHECK=PASS");
console.log("NO_FAKE_POSTS=PASS");
console.log("IDEMPOTENCY_CONSTRAINT=PASS");
console.log("DOMAIN_VALIDATION_SOURCE_PRESENT=PASS");
